In [2]:
from sklearn import datasets
iris = datasets.load_iris(as_frame=True)
X, y = iris.data, iris.target
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [3]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [6]:
iris_raw = datasets.load_iris()  # no as_frame
iris_raw['data']    # numpy array of features
iris_raw['target']  # numpy array of labels (0/1/2)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris['frame']

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X,y,test_size=0.3, random_state=42,stratify=y)
print("X_train is:", X_train) #first column is the index number of the original dataframe.

X_train is:      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3
..                 ...               ...                ...               ...
37                 4.9               3.6                1.4               0.1
79                 5.7               2.6                3.5               1.0
33                 5.5               4.2                1.4               0.2
94                 5.6               2.7                4.2               1.3
3                  4.6               3.1                1.5               0.2

[105 rows x 4 columns]

In [9]:
print("X_test is:", X_test)

X_test is:      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
107                7.3               2.9                6.3               1.8
63                 6.1               2.9                4.7               1.4
133                6.3               2.8                5.1               1.5
56                 6.3               3.3                4.7               1.6
127                6.1               3.0                4.9               1.8
140                6.7               3.1                5.6               2.4
53                 5.5               2.3                4.0               1.3
69                 5.6               2.5                3.9               1.1
20                 5.4               3.4                1.7               0.2
141                6.9               3.1                5.1               2.3
14                 5.8               4.0                1.2               0.2
38                 4.4               3.0                1.3               0.2
108                6.7               2.5                5.8               1.8
116                6.5               3.0                5.5               1.8
28                 5.2               3.4                1.4               0.2
148                6.2               3.4                5.4               2.3
57                 4.9               2.4                3.3               1.0
10                 5.4               3.7                1.5               0.2
23                 5.1               3.3                1.7               0.5
18                 5.7               3.8                1.7               0.3
97                 6.2               2.9                4.3               1.3
7                  5.0               3.4                1.5               0.2
75                 6.6               3.0                4.4               1.4
104                6.5               3.0                5.8               2.2
138                6.0               3.0                4.8               1.8
51                 6.4               3.2                4.5               1.5
84                 5.4               3.0                4.5               1.5
93                 5.0               2.3                3.3               1.0
66                 5.6               3.0                4.5               1.5
35                 5.0               3.2                1.2               0.2
134                6.1               2.6                5.6               1.4
132                6.4               2.8                5.6               2.2
85                 6.0               3.4                4.5               1.6
49                 5.0               3.3                1.4               0.2
111                6.4               2.7                5.3               1.9
40                 5.0               3.5                1.3               0.3
42                 4.4               3.2                1.3               0.2
2                  4.7               3.2                1.3               0.2
43                 5.0               3.5                1.6               0.6
77                 6.7               3.0                5.0               1.7
55                 5.7               2.8                4.5               1.3
22                 4.6               3.6                1.0               0.2
106                4.9               2.5                4.5               1.7
147                6.5               3.0                5.2               2.0
58                 6.6               2.9                4.6               1.3

In [ ]:
print("y_train is:\n", y_train) #target values corresponding to the rows in X_train

y_train is:
 98     1
68     1
19     0
143    2
99     1
      ..
37     0
79     1
33     0
94     1
3      0
Name: target, Length: 105, dtype: int32

In [13]:
print("y_test is:\n", y_test) #target values corresponding to the rows in X_test

y_test is:
 107    2
63     1
133    2
56     1
127    2
140    2
53     1
69     1
20     0
141    2
14     0
38     0
108    2
116    2
28     0
148    2
57     1
10     0
23     0
18     0
97     1
7      0
75     1
104    2
138    2
51     1
84     1
93     1
66     1
35     0
134    2
132    2
85     1
49     0
111    2
40     0
42     0
2      0
43     0
77     1
55     1
22     0
106    2
147    2
58     1
Name: target, dtype: int32